apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-conf
data:
  bitcoin.conf: |
    [regtest]
    rpcallowip=0.0.0.0/0
    rpcbind=0.0.0.0:{{ .Values.ports.regtest }}
    rpcbind=127.0.0.1:{{ .Values.ports.regtest }}
    rpcuser={{ .Values.bitcoin.user }}
    rpcpassword={{ .Values.bitcoin.password }}
