{{- if .Values.contracts.useRegtest}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels.regtest.name }}
spec:
  replicas: {{ .Values.labels.regtest.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.regtest.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.regtest.name }}
    spec:
      containers:
        - name: {{ .Values.labels.regtest.name }}
          image: {{ .Values.deployments.regtest.image }}
          command: ["bitcoind", "-regtest", "-txindex"]
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.ports.regtest }}
          volumeMounts:
            - mountPath: /root/.bitcoin
              name: {{ .Values.volumes.bitcoin.name }}
            - mountPath: /root/.bitcoin/bitcoin.conf
              name: bitcoin-conf-volume
              subPath: bitcoin_conf_path
          envFrom:
            - configMapRef:
                name: {{ .Values.labels.ord.name }}-secret
      volumes:
        - name: {{ .Values.volumes.bitcoin.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.bitcoin.claimName }}
        - name: bitcoin-conf-volume
          configMap:
            name: bitcoin-conf
            items:
            - key: bitcoin.conf
              path: bitcoin_conf_path
{{- end }}
