version: "3"

services:
  regtest:
    image: bitcoin/bitcoin:28.1
    restart: always
    ports:
      - 18443:18443
    entrypoint: bitcoind -regtest -txindex
    volumes:
      - bitcoin:/root/.bitcoin
      - ./packages/regtest/bitcoin.conf:/root/.bitcoin/bitcoin.conf
  ord:
    image: brandonjroberts/ord:0.22.2-ca9950a1
    restart: always
    ports:
      - 8553:8553
    entrypoint: ord --regtest --bitcoin-rpc-url http://broly-regtest-1:18443 --bitcoin-rpc-username user --bitcoin-rpc-password password --bitcoin-data-dir /root/.bitcoin server --http-port 8553
    links:
      - regtest
    volumes:
      - bitcoin:/root/.bitcoin
  ordinit:
    build:
      dockerfile: ./Dockerfile.ordinit
      context: packages/regtest
    depends_on:
      - ord
    restart: no
    volumes:
      - bitcoin:/root/.bitcoin
      - ./packages/regtest/bitcoin.conf:/root/.bitcoin/bitcoin.conf
  reginit:
    build:
      dockerfile: ./Dockerfile.reginit
      context: packages/regtest
    depends_on:
      ord:
        condition: service_started
      ordinit:
        condition: service_completed_successfully
    volumes:
      - bitcoin:/root/.bitcoin
      - ./packages/regtest/bitcoin.conf:/root/.bitcoin/bitcoin.conf
  updater:
    build:
      dockerfile: ./Dockerfile.update
      context: packages/regtest
    restart: always
    depends_on:
      ord:
        condition: service_started
      ordinit:
        condition: service_completed_successfully
      reginit:
        condition: service_completed_successfully
    environment:
      - REGTEST_HOST=broly-regtest-1
    volumes:
      - bitcoin:/root/.bitcoin
      - ./packages/regtest/bitcoin.conf:/root/.bitcoin/bitcoin.conf
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis:/data
  postgres:
    image: postgres:14.11-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./apps/backend/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=broly-user
      - POSTGRES_DB=broly-db
  backend:
    build:
      dockerfile: apps/backend/Dockerfile
      context: .
    ports:
      - 8080:8080
    links:
      - redis
      - postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - CONFIG_PATH=/configs/config.yaml
    volumes:
      - ./inscriptions:/app/inscriptions
  websockets:
    build:
      dockerfile: apps/backend/Dockerfile.websockets
      context: .
    ports:
      - 8083:8083
    links:
      - consumer
    restart: always
  consumer:
    build:
      dockerfile: apps/backend/Dockerfile.consumer
      context: .
    ports:
      - 8081:8081
    links:
      - redis
      - postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - CONFIG_PATH=/configs/config.yaml
      - BROLY_ORDERBOOK_CONTRACT_ADDRESS=0x072ec18edfe884b11ced172ecda723da1951cee9ed093839bcd3caa4f177f5ac
  inscriber:
    build:
      dockerfile: apps/backend/Dockerfile.inscriber
      context: .
    links:
      - backend
      - indexer
      - ord
      - regtest
      - updater
    restart: always
    environment:
      - CONFIG_PATH=/configs/config.yaml
      - SCRIPT_CONFIG_PATH=/configs/script-config.yaml
      - KEYSTORE_PATH=/app/account/test.key
      - ACCOUNT_FILE=/app/account/account.json
      - BROLY_ORDERBOOK_CONTRACT_ADDRESS=0x072ec18edfe884b11ced172ecda723da1951cee9ed093839bcd3caa4f177f5ac
      - BITCOIN_RPC_URL=http://broly-regtest-1:18443
      - BITCOIN_RPC_USER=user
      - BITCOIN_RPC_PASSWORD=password
      - BITCOIN_DATA_DIR=/root/.bitcoin
      - ORD_SERVER_URL=http://broly-ord-1:8553
    volumes:
      - bitcoin:/root/.bitcoin
      - ./account:/app/account
  indexer:
    build:
      dockerfile: packages/indexer/Dockerfile
      context: .
    links:
      - backend
    environment:
      - BROLY_CONTRACT_ADDRESS=0x072ec18edfe884b11ced172ecda723da1951cee9ed093839bcd3caa4f177f5ac
      - AUTH_TOKEN=${APIBARA_AUTH_TOKEN}
      - CONSUMER_TARGET_URL=http://broly-consumer-1:8081/consume-indexer-msg
      - APIBARA_STREAM_URL=https://sepolia.starknet.a5a.ch
      - PERSIST_TO_REDIS=redis://broly-redis-1:6379
      - INDEXER_ID=broly-indexer-id
    restart: on-failure
    depends_on:
      - consumer
  frontend:
    build:
      dockerfile: apps/web/Dockerfile
      context: .
    ports:
      - 5173:5173
    links:
      - backend
    environment:
      - VITE_STRK_CONTRACT_ADDRESS=0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d
      - VITE_BROLY_CONTRACT_ADDRESS=0x072ec18edfe884b11ced172ecda723da1951cee9ed093839bcd3caa4f177f5ac
      - VITE_USE_MOCK=false
    volumes:
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./apps/web/package.json:/app/apps/web/package.json
      - ./apps/web/public/:/app/apps/web/public
      - ./apps/web/src:/app/apps/web/src

volumes:
  redis:
  postgres:
  bitcoin:
