apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.labels.backend.name }}-secret
  labels:
    app: {{ .Values.labels.backend.name }}
data:
  BROLY_ORDERBOOK_CONTRACT_ADDRESS: {{ .Values.contracts.brolyOrderbookContract }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  CONFIG_PATH: /configs/config.yaml
