apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: broly-btc-static-ip
    networking.gke.io/managed-certificates: broly-managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - path: /ws
    pathType: Exact
    backend:
      service:
        name: {{ .Values.labels.websockets.name }}
        port:
          number: {{ .Values.ports.websockets }}
  - path: /inscriptions
    pathType: Prefix
    backend:
      service:
        name: {{ .Values.labels.backend.name }}
        port:
          number: {{ .Values.ports.backend }}
  - http:
      paths:
      - path: /ws
        pathType: Exact
        backend:
          service:
            name: {{ .Values.labels.websockets.name }}
            port:
              number: {{ .Values.ports.websockets }}
      - path: /inscriptions
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.labels.backend.name }}
            port:
              number: {{ .Values.ports.backend }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.labels.backend.name }}
            port:
              number: {{ .Values.ports.backend }}

