apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.labels.consumer.name }}-secret
  labels:
    app: {{ .Values.labels.consumer.name }}
data:
  BROLY_ORDERBOOK_CONTRACT_ADDRESS: {{ .Values.contracts.brolyOrderbookContract }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}

