apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.labels.inscriber.name }}-secret
  labels:
    app: {{ .Values.labels.inscriber.name }}
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  CONFIG_PATH: /configs/config.yaml
  SCRIPT_CONFIG_PATH: /configs/script-config.yaml
  KEYSTORE_PATH: /app/account/test.key
  ACCOUNT_FILE: /app/account/account.json
  BROLY_ORDERBOOK_CONTRACT_ADDRESS: {{ .Values.contracts.brolyOrderbookContract }}
  BITCOIN_RPC_URL: {{ .Values.bitcoin.rpcUrl }}
  BITCOIN_RPC_USER: {{ .Values.bitcoin.user }}
  BITCOIN_RPC_PASSWORD: {{ .Values.bitcoin.password }}
  BITCOIN_DATA_DIR: /root/.bitcoin
  ORD_SERVER_URL: {{ .Values.bitcoin.ordUrl }}
