Api:
  Host: localhost
  Port: 8080
  AllowOrigins:
    - '*'
  AllowMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  AllowHeaders:
    - Content-Type
  Production: false
  Admin: true
Websocket:
  Host: localhost
  Port: 8083
Consumer:
  Host: localhost
  Port: 8081
Postgres:
  Host: localhost
  Port: 5432
  User: broly-user
  Name: broly-db
