Api:
  Host: broly-backend-1
  Port: 8080
  AllowOrigins:
    - '*'
  AllowMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  AllowHeaders:
    - Content-Type
  Production: false
  Admin: true
Consumer:
  Host: broly-consumer-1
  Port: 8081
Postgres:
  Host: broly-postgres-1
  Port: 5432
  User: broly-user
  Name: broly-db
