Api:
  Port: 8080
  AllowOrigins:
    - '*'
  AllowMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  AllowHeaders:
    - Content-Type
  Production: false
  Admin: true
Postgres:
  Host: localhost
  Port: 5432
  User: broly-user
  Name: broly-db
