Api:
  Host: backend.broly-sepolia.svc.cluster.local
  Port: 8080
  AllowOrigins:
    - '*'
  AllowMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  AllowHeaders:
    - Content-Type
  Production: true
  Admin: true
Websocket:
  Host: websockets.broly-sepolia.svc.cluster.local
  Port: 8083
Consumer:
  Host: consumer.broly-sepolia.svc.cluster.local
  Port: 8081
Postgres:
  Host: postgres.broly-sepolia.svc.cluster.local
  Port: 5432
  User: broly-user
  Name: broly-db
